"""Add review system and spaced repetition

Revision ID: b450be27b186
Revises: 3be6e30d5554
Create Date: 2025-10-17 00:27:57.964168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b450be27b186'
down_revision = '3be6e30d5554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_interval_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('questions_answered', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_column('questions_answered')
        batch_op.drop_column('review_interval_days')
        batch_op.drop_column('review_count')
        batch_op.drop_column('next_review_date')
        batch_op.drop_column('last_reviewed_at')

    # ### end Alembic commands ###
